import 'normalize.css'
import 'prismjs/themes/prism-solarizedlight.css'

import './src/styles/global.css'
import './src/styles/font.css'
import './src/styles/about.css'
import './src/styles/containers.css'
import './src/styles/navbar.css'
import './src/styles/posts.css'
import './src/styles/post.css'
